// Advent of Code 2023, Day 10.
// By Sebastian Raaphorst, 2023.

package day11

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class Day11Test {
    companion object {
        private val input = """
            ....#........
            .........#...
            #............
            .............
            .............
            ........#....
            .#...........
            ............#
            .............
            .............
            .........#...
            #....#.......
        """.trimIndent()
    }

    @Test
    fun `Problem 1 example`() {
        assertEquals(374, answer1(input))
    }

    @Test
    fun `Problem 2 example`() {
    }
}
